on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: myops-git/gh-action@v2
      
      - run: echo random-number ${{ steps.foo.input.secret_input }}
        shell: bash
